remote_theme: "mmistakes/minimal-mistakes@4.16.6"
title: Urban Tech Hub 
subtitle: at the Jacobs Technion-Cornell Institute
url: "http://jacobs-technion-cornell-institute.github.io" # the base hostname & protocol for your site
search: true
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

logo: assets/jacobs-logo-88x88.jpg

include:
  - _pages

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: https://twitter.com/ny_jacobs
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/jacobs-technion-cornell-institute

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
