remote_theme: "mmistakes/minimal-mistakes@4.16.6"
title: Urban Tech Hub 
subtitle: at the Jacobs Technion-Cornell Institute
url: "http://jacobs-technion-cornell-institute.github.io" # the base hostname & protocol for your site
search: true
plugins:
  - jekyll-sitemap
  - jekyll-include-cache
  
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
